# Generated by Django 4.0.4 on 2022-09-20 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_attendancetotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student')),
            ],
            options={
                'verbose_name_plural': 'Marks',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='MarksClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Quiz 1', 'Quiz 1'), ('Quiz 2', 'Quiz 2'), ('Quiz 3', 'Quiz 3'), ('Assignment', 'Assignment'), ('Presentation', 'Presentation'), ('Viva', 'Viva'), ('Attendance', 'Attendance'), ('Mid Term Exam', 'Mid Term Exam'), ('Final Exam', 'Final Exam')], default='Quiz 1', max_length=50)),
                ('status', models.BooleanField(default='False')),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.assign')),
            ],
            options={
                'unique_together': {('assign', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Quiz 1', 'Quiz 1'), ('Quiz 2', 'Quiz 2'), ('Quiz 3', 'Quiz 3'), ('Assignment', 'Assignment'), ('Presentation', 'Presentation'), ('Viva', 'Viva'), ('Attendance', 'Attendance'), ('Mid Term Exam', 'Mid Term Exam'), ('Final Exam', 'Final Exam')], default='Quiz 1', max_length=50)),
                ('marks1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('studentcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.studentcourse')),
            ],
            options={
                'unique_together': {('studentcourse', 'name')},
            },
        ),
    ]
